# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RIT_1class <- function(z, weights, L, branch, depth, n_trees, min_inter_sz, n_cores, is_sparse) {
    .Call('iRF_RIT_1class', PACKAGE = 'iRF', z, weights, L, branch, depth, n_trees, min_inter_sz, n_cores, is_sparse)
}

RIT_2class <- function(z, z0, L, branch, depth, n_trees, theta0, theta1, min_inter_sz, n_cores, is_sparse) {
    .Call('iRF_RIT_2class', PACKAGE = 'iRF', z, z0, L, branch, depth, n_trees, theta0, theta1, min_inter_sz, n_cores, is_sparse)
}

nodeVars <- function(varnodes, nrnodes, p, parents, idcskeep, nodect, rowoffset, nodevars) {
    .Call('iRF_nodeVars', PACKAGE = 'iRF', varnodes, nrnodes, p, parents, idcskeep, nodect, rowoffset, nodevars)
}

