# Despite the warning below, I still edited this file to make some legacy piece of code work.
# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RIT_1class <- function(z, weights, L, branch, depth, n_trees, min_inter_sz, n_cores, is_sparse) {
    rv <- .Call('iRF_RIT_1class', PACKAGE = 'iRF', z, weights, L, branch, depth, n_trees, min_inter_sz, n_cores, is_sparse)
}

RIT_2class <- function(z, z0, L, branch, depth, n_trees, theta0, theta1, min_inter_sz, n_cores, is_sparse) {
    rv <- .Call('iRF_RIT_2class', PACKAGE = 'iRF', z, z0, L, branch, depth, n_trees, theta0, theta1, min_inter_sz, n_cores, is_sparse)
}

ancestorPath <- function(treeInfo, nodeVarIndices, p, nleaf, firstSplit) {
    .Call('iRF_ancestorPath', PACKAGE = 'iRF', treeInfo, nodeVarIndices, p, nleaf, firstSplit)
}

